Skip device update if payload is empty
itavero/homebridge-z2m pull request #78
Opened 2021-02-25 11:37 UTC by jkimbo

When renaming a device zigbee2mqtt sends a message with an empty payload to the old device topic (see https://github.com/Koenkk/zigbee2mqtt/blob/6484feecb7c4727c0623a8a6264bac8b3403bbb3/lib/extension/bridge.js#L390) and this breaks the JSON parsing resulting in an error in the logs. 

This PR checks that the payload is not empty before trying to parse it as JSON. It also adds the raw payload to the logs if the JSON parsing fails to any other reason so that it's easier to debug this issue in the future.

---

BTW thanks for this great library! Just started using it and it's so useful.

2021-02-25 13:50 UTC, itavero commented
Thanks for your contribution. Added a minor comment.  Not sure why the build is failing though, I'll try to have a look later tonight.

2021-02-25 19:59 UTC, jkimbo commented
@itavero I can't see your comment for some reason?

2021-02-26 11:03 UTC, itavero requested changes

2021-02-26 11:04 UTC, itavero commented
@jkimbo  Apparently I had to click an additional button to actually publish the comment ;)

I haven't been able to look into why the build is failing. It appears that for your PR somehow the token for SonarCloud isn't available. Probably a rights issue in GitHub that I should fix somehow.

2021-02-26 13:30 UTC, jkimbo commented on src/platform.ts
> +        this.log.info(`Payload: ${statePayload}`);
👍 updated

2021-02-26 15:15 UTC, itavero approved these changes
Changes approved.

I will still leave this open for a bit, so I can hopefully figure out what's wrong with the SonarCloud integration. 😅

2021-02-26 16:41 UTC, itavero commented
I tried to rebase your branch up on the `master` branch but somehow the GitHub Desktop app messed up.

2021-02-26 19:59 UTC, merged

2021-02-26 20:00 UTC, itavero commented
@jkimbo Merged your changes. They will be included in the next release. Thanks again for your contribution! 👍

2021-02-27 09:01 UTC, jkimbo commented
Thanks!

2021-03-03 21:08 UTC, itavero commented
Now available in v1.1.2